=== opf-labs/ots-schema/src/edu/harvard/hul/ois/ots/schemas/xsd/docmd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Editor: Florida Center for Library Automation (FCLA) and Harvard University Library (HUL)
	Released: March 17, 2009
	June 2, 2010 Change: Make PageCount element optional to account for PDFs whose pageCount cannot be determined.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:docmd="http://www.fcla.edu/dls/md/docmd" targetNamespace="http://www.fcla.edu/docmd" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="document">
		<xs:complexType>
		   <xs:sequence>
			<xs:element name="PageCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="WordCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CharacterCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ParagraphCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LineCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="TableCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GraphicsCount" minOccurs="0" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Language" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
			<xs:element name="Font" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="FontName" type="xs:string"/>
					<xs:attribute name="isEmbedded" type="xs:boolean"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Features" minOccurs="0" maxOccurs="unbounded">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="isTagged"/>
						<xs:enumeration value="hasOutline"/>
						<xs:enumeration value="hasThumbnails"/>
						<xs:enumeration value="hasLayers"/>
						<xs:enumeration value="hasForms"/>
						<xs:enumeration value="hasAnnotations"/>
						<xs:enumeration value="hasAttachments"/>
						<xs:enumeration value="useTransparency"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		   </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== opf-labs/ots-schema/test_xml/docmdsample.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns="http://www.fcla.edu/docmd" xmlns:docmd="http://www.fcla.edu/dls/md/docmd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fcla.edu/docmd http://www.fcla.edu/dls/md/docmd.xsd">
	<PageCount>3</PageCount>
	<WordCount>34</WordCount>
	<CharacterCount>4</CharacterCount>
	<ParagraphCount>4</ParagraphCount>
	<LineCount>66</LineCount>
	<TableCount>0</TableCount>
	<GraphicsCount>4</GraphicsCount>
	<Language>234</Language>
	<Language>blah</Language>
	<Font FontName="BookmanOldStyle" isEmbedded="false"/>
	<Font FontName="Arial,Bold" isEmbedded="false"/>
	<Font FontName="TimesNewRoman,Italic" isEmbedded="false"/>
	<Features>hasLayers</Features>
	<Features>hasOutline</Features>
</document>
